name: Pull Request checks

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  ACCOUNT: ${{ secrets.ACCOUNT }}
  USER: ${{ secrets.USER }}
  PASSWORD: ${{ secrets.PASSWORD }}
  DATABASE: ${{ secrets.DATABASE }}
  SCHEMA: ${{ secrets.SCHEMA }}
  WAREHOUSE: ${{ secrets.WAREHOUSE }}

defaults:
  run:
    shell: bash -el {0}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          activate-environment: snowpark
          environment-file: environment.yml

      - name: Run tests
        run: python -m pytest 

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          activate-environment: snowpark
          environment-file: environment.yml
      
      - name: Install dependencies
        run: pip install pylint
      
      - name: Analysing the code with pylint
        run: pylint $(git ls-files '*.py')
